echo  "we will start working on the tropical project for visa"
echo " all developers must install git and github"
echo "all hands on deck"
echo "we will work in a scrum enviromnent and sprint for two weeks"
echo "I am adding more information to the data base"
echo "make sure you commit information before you close"
